### ISSUE TITLE
Error while running rails generate startup_framework:install <Startup Framework Directory>

### ISSUE THREAD

**Issue by aman199002** [vertmac/designmodo-startup_framework-rails#1]
I have downloaded startup framework. But when i am trying to intsall it using:

```
$ rails generate startup_framework:install <Startup Framework Directory>
```

I am getting an error:

No such file or directory - /Users/aman/Downloads/startup framework/common-files/css/images/bx_loader.gif (Errno::ENOENT)

**Comment by ronban** [comment]
Your download folder looks wrong. There should be a developer and designer
on top and these files should then come automatically in place. But I will
check whether the code to copy these image is right or not.

On 05-Jun-2014, at 10:40 am, aman garg notifications@github.com wrote:

I have downloaded startup framework. But when i am trying to intsall it
using:

$ rails generate startup_framework:install <Startup Framework Directory>

I am getting an error:

No such file or directory - /Users/aman/Downloads/startup
framework/common-files/css/images/bx_loader.gif (Errno::ENOENT)

—
Reply to this email directly or view it on GitHub
https://github.com/vertmac/designmodo-startup_framework-rails/issues/1.

**Comment by ronban** [comment]
Closing this if you have got the correct directory.
